services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
      POSTGRES_PORT: 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  backend:
    image: golang
    build:
      context: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8019"
    env_file:
      - app.env

volumes:
  db_data:
